### ISSUE TITLE
Building backends on Gambit v2.4

### ISSUE THREAD

**Issue by aseshkdatta** [GambitBSM/gambit_2.4#8]
Hi,

I've tried to build the Gambit backends one by one on a single thread.

A few of the backends were not found and trying to build them prompts
the generic message:

make: *** No rule to make target 'backend_name'.  Stop.

These are: 
ATLAS_FullLikes, contur, darkages,directdm, feynhiggs,
montepythonlike, prospino, classy, pbarlike & salami.

"make acropolis" ran successfully but is being shown
as "absent/broken  0      0       0"  with  "./gambit backends"

For DarkSUSY, I tried with the following three options
1. make darksusy_MSSM
2. make darksusy_generic_wimp
3. make darksusy_all_models

Backends could only be produced for the MSSM and the 
generic_wimp case.

However, when test-run gambit with
    ./gambit -f yaml_files/MSSM7.yaml   (or, MSSM9.yaml),
 I get the following error message.

Could you please observe and let me know where I might
have gone wrong.

Thanks.
Asesh

------------------------------------------------------------------------------------------------- 
Starting GAMBIT
----------
Running in MPI-parallel mode with 1 processes
----------
Running with 32 OpenMP threads per MPI process (set by the environment variable OMP_NUM_THREADS).
YAML file: yaml_files/MSSM7.yaml
Importing: include/StandardModel_SLHA2_scan.yaml
Initialising logger...  log_debug_messages = true; log messages tagged as 'Debug' WILL be logged. 
WARNING: This may lead to very large log files!
Rank 0 resume flag? 1
Rank 0: output file readable? 1(filename: runs/MSSM7//samples//MSSM7.hdf5)
Resolving dependencies and backend requirements.  Hang tight...

 FATAL ERROR

GAMBIT has exited with fatal exception: GAMBIT error
ERROR: A problem has been raised by the dependency resolver subsystem.
None of the vertex candidates for
unimproved_MSSM_spectrum (Spectrum), required by MSSM_spectrum (Spectrum) [make_MSSM_precision_spectrum_none, PrecisionBit]
fulfills all rules in the YAML file.
Please check your YAML file for contradictory rules, and
ensure that you have built GAMBIT in the first place with
all of the components that you are trying to use.
Raised at: line 1401 in function Gambit::DRes::VertexID Gambit::DRes::DependencyResolver::resolveDependencyFromRules(const VertexID&, const sspair&) of /home/asesh/Packages/Gambit-BSM/gambit_2.4/Core/src/depresolver.cpp.
Calling MPI_Finalize...
-------------------------------------------------------------------------------------------------------

**Comment by tegonzalo** [comment]
> ATLAS_FullLikes, contur, darkages,directdm, feynhiggs,
> montepythonlike, prospino, classy, pbarlike & salami.

Most of these backends are written in python, so they require pybind11. You disabled that earlier because it wasn't working for you due to the segfault. The exceptions are prospino, which is work in progress so it won't work at this stage, and FeynHiggs, that is incompatible with modern compilers in the version that is interfaces. We are working to interface a more modern version of FH, which should be ready soon.


> * make darksusy_MSSM

I am surprised that this didn't work. Which version of DarkSUSY are you trying to build here? Anything before 6.4 used the old versions of FeynHiggs internally, so they won't work, but 6.5 uses the new version, so it should.

Lastly, the run error you see is because you don't have any FlexibleSUSY models installed. When running cmake add the following flag `-DBUILD_FS_MODELS=MSSM` and rebuild gambit

**Comment by aseshkdatta** [comment]
Thank you so much for a detailed look into the issues and your suggestions.

I'm following those up.

Asesh K Datta

**Comment by aseshkdatta** [comment]
You can close the issue now.

Thanks again.
Asesh K Datta
